#    Copyright 2018 ARM Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import logging

from wa.framework import pluginloader
from wa.framework.exception import ConfigError
from wa.framework.instrument import is_installed, Instrument
from wa.framework.plugin import Plugin
from wa.utils.log import log_error, indentcontext
from wa.utils.misc import isiterable
from wa.utils.types import identifier
from typing import List, Union, TYPE_CHECKING, cast
from types import ModuleType
if TYPE_CHECKING:
    from wa.framework.execution import ExecutionContext
    from wa.commands.process import ProcessContext


class OutputProcessor(Plugin):
    """
    These post-process metrics and artifacts generated by workloads or
    instruments, as well as target metadata collected by WA, in order to
    generate additional metrics and/or artifacts (e.g. generating statistics
    or reports). Output processors are also used to export WA output
    externally (e.g. upload to a database).
    """
    kind: str = 'output_processor'
    requires: List[Union[str, Instrument]] = []

    def __init__(self, **kwargs):
        super(OutputProcessor, self).__init__(**kwargs)
        self.is_enabled = True

    def validate(self) -> None:
        """
        validate whether requirements are satisfied
        """
        super(OutputProcessor, self).validate()
        for instrument in self.requires:
            if not is_installed(instrument):
                msg = 'Instrument "{}" is required by {}, but is not installed.'
                raise ConfigError(msg.format(instrument, self.name))

    def initialize(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        pass

    def finalize(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        pass


class ProcessorManager(object):
    """
    manage the output processors
    """
    def __init__(self, loader: ModuleType = pluginloader):
        self.loader = loader
        self.logger = logging.getLogger('processor')
        self.processors: List[OutputProcessor] = []

    def install(self, processor: OutputProcessor, context: Union['ExecutionContext', 'ProcessContext']):
        """
        install output processor
        """
        if not isinstance(processor, OutputProcessor):
            processor = self.loader.get_output_processor(processor)
        self.logger.debug('Installing {}'.format(processor.name))
        processor.logger.context = context  # type:ignore
        self.processors.append(processor)
        context.add_augmentation(processor)

    def disable_all(self) -> None:
        """
        disable all output processors
        """
        for output_processor in self.processors:
            self._disable_output_processor(output_processor)

    def enable_all(self) -> None:
        """
        enable all output processors
        """
        for output_processor in self.processors:
            self._enable_output_processor(output_processor)

    def enable(self, to_enable: Union[str, List[OutputProcessor], OutputProcessor]) -> None:
        """
        enable the specified output processor
        """
        if isiterable(to_enable):
            for inst in to_enable:  # type:ignore
                self._enable_output_processor(cast(OutputProcessor, inst))
        else:
            self._enable_output_processor(cast(OutputProcessor, to_enable))

    def disable(self, to_disable: Union[str, List[OutputProcessor], OutputProcessor]) -> None:
        """
        disable the specified output processor
        """
        if isiterable(to_disable):
            for inst in to_disable:  # type:ignore
                self._disable_output_processor(cast(OutputProcessor, inst))
        else:
            self._disable_output_processor(cast(OutputProcessor, to_disable))

    def get_output_processor(self, processor: Union[OutputProcessor, str]) -> OutputProcessor:
        """
        get output processor
        """
        if isinstance(processor, OutputProcessor):
            return processor

        processor = identifier(processor)
        for p in self.processors:
            if processor == p.name:
                return p
        raise ValueError('Output processor {} is not installed'.format(processor))

    def get_enabled(self) -> List[OutputProcessor]:
        """
        get enabled output processors
        """
        return [p for p in self.processors if p.is_enabled]

    def get_disabled(self) -> List[OutputProcessor]:
        """
        get disabled output processors
        """
        return [p for p in self.processors if not p.is_enabled]

    def validate(self) -> None:
        """
        validate the output processors
        """
        for proc in self.processors:
            proc.validate()

    def initialize(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        """
        initialize the output processor
        """
        for proc in self.processors:
            proc.initialize(context)

    def finalize(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        """
        finalize the output processor
        """
        for proc in self.processors:
            proc.finalize(context)

    def process_job_output(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        """
        process job output
        """
        self.do_for_each_proc('process_job_output', 'Processing using "{}"',
                              context.job_output, context.target_info,
                              context.run_output)

    def export_job_output(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        """
        export job output
        """
        self.do_for_each_proc('export_job_output', 'Exporting using "{}"',
                              context.job_output, context.target_info,
                              context.run_output)

    def process_run_output(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        """
        process run output
        """
        self.do_for_each_proc('process_run_output', 'Processing using "{}"',
                              context.run_output, context.target_info)

    def export_run_output(self, context: Union['ExecutionContext', 'ProcessContext']) -> None:
        """
        export run output
        """
        self.do_for_each_proc('export_run_output', 'Exporting using "{}"',
                              context.run_output, context.target_info)

    def do_for_each_proc(self, method_name: str, message: str, *args) -> None:
        """
        run the method for each processor
        """
        with indentcontext():
            for proc in self.processors:
                if proc.is_enabled:
                    proc_func = getattr(proc, method_name, None)
                    if proc_func is None:
                        continue
                    try:
                        self.logger.info(message.format(proc.name))
                        proc_func(*args)
                    except Exception as e:  # pylint: disable=broad-except
                        if isinstance(e, KeyboardInterrupt):
                            raise
                        log_error(e, self.logger)

    def _enable_output_processor(self, inst: OutputProcessor) -> None:
        """
        enable output processor
        """
        inst = self.get_output_processor(inst)
        self.logger.debug('Enabling output processor {}'.format(inst.name))
        if not inst.is_enabled:
            inst.is_enabled = True

    def _disable_output_processor(self, inst: OutputProcessor) -> None:
        """
        disable output processor
        """
        inst = self.get_output_processor(inst)
        self.logger.debug('Disabling output processor {}'.format(inst.name))
        if inst.is_enabled:
            inst.is_enabled = False
